import { useEffect, useState } from "react";
import api from "../api";

function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function loadAlerts() {
      try {
        const response = await api.get("/alerts");
        setAlerts(response.data.alerts ?? response.data ?? []);
      } catch {
        setError("Unable to load alerts.");
      } finally {
        setLoading(false);
      }
    }

    loadAlerts();
  }, []);

  return (
    <main className="main">
      <div className="page-heading">
        <div>
          <p className="eyebrow">Detection</p>
          <h1>Alerts</h1>
          <p className="page-subtitle">
            Detections generated by ChiSoSecure security rules.
          </p>
        </div>
      </div>

      <section className="data-section">
        <div className="data-toolbar">
          <span>{alerts.length} alerts</span>
        </div>

        {loading && <p className="state-message">Loading alerts...</p>}
        {error && <p className="state-message error-text">{error}</p>}

        {!loading && !error && (
          <div className="data-table">
            <div className="data-row data-header alerts-grid">
              <span>ID</span>
              <span>Event</span>
              <span>Detection</span>
              <span>Severity</span>
              <span>Message</span>
              <span>Created</span>
            </div>

            {alerts.map((alert) => (
              <div className="data-row alerts-grid" key={alert.id}>
                <span className="mono">#{alert.id}</span>
                <span className="mono">#{alert.event_id}</span>
                <strong>{alert.rule_name}</strong>
                <span>
                  <span className={`severity severity-${alert.severity?.toLowerCase()}`}>
                    {alert.severity}
                  </span>
                </span>
                <span>{alert.message}</span>
                <span className="muted-cell">
                  {alert.created_at
                    ? new Date(alert.created_at).toLocaleString()
                    : "—"}
                </span>
              </div>
            ))}

            {alerts.length === 0 && (
              <div className="empty-state">No alerts found.</div>
            )}
          </div>
        )}
      </section>
    </main>
  );
}

export default Alerts;